apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testchat-apprhoai 
  janus-idp.io/tekton: testchat-apprhoai
  backstage.io/kubernetes-id: testchat-apprhoai
  backstage.io/kubernetes-namespace: testns 
  app.kubernetes.io/part-of: testchat-apprhoai
resources: 
- application-dev.yaml