apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testchat-apprhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchat-apprhoai 
  name: testchat-apprhoai
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testchat-apprhoai 
    weight: 100 
  wildcardPolicy: None
